# ---------- IMPORT MODULES ----------
import streamlit as st  # Main Streamlit library
from streamlit_javascript import st_javascript  # For handling JavaScript events
import streamlit.components.v1 as components  # To embed custom HTML/JS
from gtts import gTTS  # Google Text-to-Speech
import base64  # For encoding audio to base64
import os  # For file handling and environment variables
from PIL import Image  # For handling images

# ---------- LOAD IMAGES ----------
home_image = Image.open("Chemistry Advance.jpeg")
solid_image = Image.open("download (3).jpeg")
liquid_image = Image.open("77ef79832178ee1d9b49576a6be52556.jpg")
gas_image = Image.open("Bright blue sky fluffy clouds nature tranquil scene generated by artificial intelligence _ Premium AI-generated image.jpeg")
plasma_image = Image.open("Beautiful northern lights in night sky over mountain northern lights in iceland _ Premium Photo.jpeg")
summary_image = Image.open("Focuses on the intersection of technology science _ Premium AI-generated image.jpeg")

# ---------- SET API KEY ----------
os.environ["OPENAI_API_KEY"] = "sk-proj-62KgIfk2xwl5DHxquC4SgsJgFIV-SBjo9J4kN35HGxW0XdDF4nYZu5l6BpHkeWQQ1MmxQWmH1tT3BlbkFJOqtCUSBjIRVs_NPQ0mqwC5b7DThar5nQxS8rAnatk5iAew28hfSqzOlaRQBqGZoCtQrMs8aOwcA"

# ---------- PAGE CONFIGURATION ----------
st.set_page_config(
    page_title='Four States Of Matter',
    page_icon='four-states-4364870.webp',
    layout='wide'
)

# ---------- SIDEBAR STYLING ----------
st.markdown("""
<style>
[data-testid="stSidebar"] { background-color: #0f3d0f; padding: 20px; border-right: 3px solid #0a290a; }
.sidebar-title { font-size: 24px; color: white; font-weight: bold; margin-bottom: 20px; }
label, .stRadio > label { color: #ccffcc !important; font-size: 16px; }
[data-baseweb="select"] { background-color: #145214 !important; color: white !important; border-radius: 10px; }
.css-1wa3eu0-placeholder { color: #ccffcc !important; }
</style>
""", unsafe_allow_html=True)

# Sidebar title
st.sidebar.markdown("<div class='sidebar-title'>My App Menu</div>", unsafe_allow_html=True)

# Sidebar page selector
page = st.sidebar.selectbox(
    "Choose:",
    ["Home", "Solid", "Liquid", "Gas", "Plasma", "Summary"]
)

# ---------- HELPER FUNCTION FOR TEXT-TO-SPEECH ----------
def tts_button(text, label="🔊 Read Loudly", key=None):
    # Button styling
    st.markdown("""
    <style>
    div.stButton > button:first-child {
        background: linear-gradient(135deg, #1dbf73, #17a65b);
        color: white;
        padding: 14px 35px;
        font-size: 20px;
        font-weight: bold;
        border-radius: 14px;
        border: none;
        cursor: pointer;
        transition: 0.25s ease-in-out;
        box-shadow: 0 0 12px rgba(0, 255, 100, 0.4);
    }
    div.stButton > button:first-child:hover {
        transform: scale(1.08);
        box-shadow: 0 0 25px rgba(0, 255, 100, 0.8);
    }
    @keyframes pulseGlow {
        0% { box-shadow: 0 0 12px rgba(0, 255, 100, 0.4); }
        50% { box-shadow: 0 0 24px rgba(0, 255, 100, 0.7); }
        100% { box-shadow: 0 0 12px rgba(0, 255, 100, 0.4); }
    }
    div.stButton > button:first-child {
        animation: pulseGlow 2s infinite;
    }
    </style>
    """, unsafe_allow_html=True)

    # Generate and play audio when button is clicked
    if st.button(label, key=key):
        # Generate TTS audio
        tts = gTTS(text=text, lang='en', slow=False)
        tts.save("temp_audio.mp3")
        
        # Read and encode audio
        with open("temp_audio.mp3", "rb") as audio_file:
            audio_bytes = audio_file.read()
            audio_base64 = base64.b64encode(audio_bytes).decode()
        
        # Auto-play audio in browser
        audio_html = f"""
        <audio autoplay>
            <source src="data:audio/mp3;base64,{audio_base64}" type="audio/mp3">
        </audio>
        """
        st.markdown(audio_html, unsafe_allow_html=True)
        st.success("Reading text...")
        
        # Delete temporary audio file
        if os.path.exists("temp_audio.mp3"):
            os.remove("temp_audio.mp3")

# ---------- PAGE CONTENT ----------
if page == 'Home':
    st.title("Four States Of Matter")
    
    # Introduction text
    text = 'Matter—everything that has mass and takes up space—exists in different forms called states of matter. The four basic states are solid, liquid, gas, and plasma. Each state has unique properties based on how closely particles are packed and how freely they move.'
    st.write(text)
    
    # Why study matter? text
    st.header('Why we study them?')
    with open('Why we study them.txt','r', encoding="utf-8") as file:
        text_2 = file.read()
    st.write(text_2)
    
    # Combine text and read with TTS button
    combined_text = text + " " + text_2
    tts_button(combined_text, label="🔊 Read Loudly", key="home_tts")

    # Display image
    st.image(home_image, caption='Chemstry')

elif page == 'Solid':
    st.title("🧱 Solid State")
    with open('Solid State.txt','r', encoding="utf-8") as file:
        text = file.read()
    st.write(text)
    tts_button(text, key="solid_tts")
    st.image(solid_image, caption='Ice')

elif page == 'Liquid':
    st.title('💧 Liquid State')
    with open('Liquid State.txt','r', encoding="utf-8") as file:
        text = file.read()
    st.write(text)
    tts_button(text, key="liquid_tts")
    st.image(liquid_image, caption='Water')

elif page == 'Gas':
    st.title("💨 Gas State")
    with open('Gas state.txt','r', encoding="utf-8") as file:
        text = file.read()
    st.write(text)
    tts_button(text, key="gas_tts")
    st.image(gas_image, caption='Clouds')

elif page == 'Plasma':
    st.title("⚡ Plasma State")
    with open('Plasma State.txt','r', encoding="utf-8") as file:
        text = file.read()
    st.write(text)
    tts_button(text, key="plasma_tts")
    st.image(plasma_image, caption='Aroura boreails')

elif page == 'Summary':
    st.title("🎯 Summary")
    with open('Summary.txt', 'r', encoding="utf-8") as file:
        text = file.read()
    st.write(text)
    tts_button(text, key="summary_tts")
    st.image(summary_image, caption='Science')
    
    # Initialize session state for finish button
    if "finish_clicked" not in st.session_state:
        st.session_state.finish_clicked = False

    # ---------- HTML + JS FINISH BUTTON ----------
    html_code = """
    <div style="text-align:center;">
    <button id="finishGame" style="
        background: linear-gradient(90deg, #00f7ff, #005eff);
        border: 4px solid #00d2ff;
        padding: 20px 45px;
        color: white;
        font-size: 32px;
        font-family: 'Press Start 2P', monospace;
        border-radius: 12px;
        cursor: pointer;
        text-shadow: 0 0 8px #00f7ff;
        box-shadow: 0 0 20px #00f7ff, 0 0 40px #005eff;
        animation: glowPulse 2s infinite;
    ">FINISH ✔️</button>
    </div>

    <audio id="boomSound" src="https://www.fesliyanstudios.com/play-mp3/4380"></audio>

    <script>
    const button = document.getElementById("finishGame");
    const sound = document.getElementById("boomSound");

    button.onclick = () => {
        sound.volume = 0.6;
        sound.play();

        // Flash effect
        let flash = document.createElement("div");
        flash.style.position="fixed";
        flash.style.top=0;
        flash.style.left=0;
        flash.style.width="100vw";
        flash.style.height="100vh";
        flash.style.background="white";
        flash.style.opacity=1;
        flash.style.pointerEvents="none";
        flash.style.animation="flashAnim 0.3s forwards";
        document.body.appendChild(flash);
        setTimeout(()=>flash.remove(),300);

        // Particles effect
        for(let i=0;i<80;i++){
            let p=document.createElement("div");
            p.style.position="fixed";
            p.style.width="10px"; p.style.height="10px";
            p.style.borderRadius="50%";
            p.style.background=["yellow","white","cyan","orange"][Math.floor(Math.random()*4)];
            p.style.left=window.innerWidth/2+"px";
            p.style.top=window.innerHeight/2+"px";
            p.style.transform="translate(0,0)";
            p.style.transition="transform 1.2s linear, opacity 1.2s linear";
            document.body.appendChild(p);
            let xMove=(Math.random()*600-300);
            let yMove=(Math.random()*600-300);
            setTimeout(()=>{p.style.transform=`translate(${xMove}px,${yMove}px)`; p.style.opacity=0;},10);
            setTimeout(()=>p.remove(),1200);
        }

        // Shake effect
        document.body.style.animation="shake 0.4s";

        // Notify Streamlit that finish was clicked
        const streamlitEvent = new CustomEvent("streamlit:finishClicked");
        window.dispatchEvent(streamlitEvent);
    };
    </script>

    <style>
    @keyframes glowPulse {0%{box-shadow:0 0 20px #00f7ff;}50%{box-shadow:0 0 40px #0077ff;}100%{box-shadow:0 0 20px #00f7ff;}}
    @keyframes shake {0%{transform:translate(0,0);}25%{transform:translate(5px,-5px);}50%{transform:translate(-5px,5px);}75%{transform:translate(5px,5px);}100%{transform:translate(0,0);} }
    @keyframes flashAnim {0%{opacity:1;}100%{opacity:0;}}
    </style>
    """

    # Embed HTML + JS finish button
    components.html(html_code, height=600)

    # Listen for finish button click using JavaScript
    js_event = st_javascript("""
    window.addEventListener("streamlit:finishClicked", ()=>{window.finishClicked=true;});
    window.finishClicked || false;
    """)

    # Trigger celebration once finish button clicked
    if js_event and not st.session_state.finish_clicked:
        st.session_state.finish_clicked = True
        st.success("🎉 PROGRAM COMPLETE! Great job! 🎉")
        st.balloons()
